spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
external:
  fraud-service-url: http://localhost:9561/api/fraud-check
  payment:
    providers:
      paypal:
        url: http://localhost:9561/v1/payments/payment
      stripe:
        url: http://localhost:9561/v1/charges
      square:
        url: http://localhost:9561/v2/payments
